name: "Docker Build and Deploy"
description: "Builds, pushes Docker image and deploys to Dokploy"

inputs:
  application-name:
    description: "Name of the service (backend, microservice)"
    required: true
  docker-image:
    description: "Docker image name (wanderlee/backend-api)"
    required: true
  service-path:
    description: "Path to service directory (./backend)"
    required: true
  version:
    description: "Version to deploy"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  dokploy-token:
    description: "Dokploy API token"
    required: true
  project-name:
    description: "Dokploy project name"
    required: true
  application-id:
    description: "Dokploy application ID (found in URL)"
    required: true
  dokploy-url:
    description: "Dokploy base URL (e.g., https://dokploy.example.com)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: echo "${{ inputs.docker-password }}" | docker login -u "${{ inputs.docker-username }}" --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        docker build \
          -t ${{ inputs.docker-image }}:${{ inputs.version }} \
          -t ${{ inputs.docker-image }}:latest \
          ${{ inputs.service-path }}

    - name: Push to Docker Hub
      shell: bash
      run: |
        docker push ${{ inputs.docker-image }}:${{ inputs.version }}
        docker push ${{ inputs.docker-image }}:latest

    - name: Update Image in Dokploy
      shell: bash
      run: |
        echo "🔄 Updating Dokploy application to image: ${{ inputs.docker-image }}:${{ inputs.version }}"
        curl -X 'POST' \
          '${{ inputs.dokploy-url }}/api/trpc/application.update?batch=1' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/j son' \
          -H 'Authorization: Bearer ${{ inputs.dokploy-token }}' \
          -d '{
            "0": {
              "json": {
                "applicationId": "${{ inputs.application-id }}",
                "dockerImage": "${{ inputs.docker-image }}:${{ inputs.version }}"
              }
            }
          }'

    - name: Deploy to Dokploy
      shell: bash
      run: |
        echo "🚀 Triggering deployment for ${{ inputs.application-name }} (ID: ${{ inputs.application-id }})"
        curl -X 'POST' \
          '${{ inputs.dokploy-url }}/api/application.deploy' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: ${{ inputs.dokploy-token }}' \
          -d '{
            "applicationId": "${{ inputs.application-id }}"
          }'

    - name: Deployment Summary
      shell: bash
      run: |
        echo "### ✅ ${{ inputs.application-name }} Deployed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ inputs.docker-image }}:${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "docker pull ${{ inputs.docker-image }}:${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
