name: "Docker Build and Deploy"
description: "Builds, pushes Docker image and deploys to Dokploy"

inputs:
  application-name:
    description: "Name of the service (backend, microservice)"
    required: true
  docker-image:
    description: "Docker image name (wanderlee/backend-api)"
    required: true
  service-path:
    description: "Path to service directory (./backend)"
    required: true
  version:
    description: "Version to deploy"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  dokploy-token:
    description: "Dokploy API token"
    required: true
  project-name:
    description: "Dokploy project name"
    required: true
  application-id:
    description: "Dokploy application ID (found in URL)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: echo "${{ inputs.docker-password }}" | docker login -u "${{ inputs.docker-username }}" --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        docker build \
          -t ${{ inputs.docker-image }}:${{ inputs.version }} \
          -t ${{ inputs.docker-image }}:latest \
          ${{ inputs.service-path }}

    - name: Push to Docker Hub
      shell: bash
      run: |
        docker push ${{ inputs.docker-image }}:${{ inputs.version }}
        docker push ${{ inputs.docker-image }}:latest

    - name: Deploy to Dokploy
      uses: Crokily/dokploy-deploy-action@v1.0.1
      with:
        dokploy_url: "https://dokploy.wanderlee.site"
        api_key: ${{ inputs.dokploy-token }}
        project_name: ${{ inputs.project-name }}
        application_name: ${{ inputs.application-name }}

    - name: Deployment Summary
      shell: bash
      run: |
        echo "### ✅ ${{ inputs.application-name }} Deployed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ inputs.docker-image }}:${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "docker pull ${{ inputs.docker-image }}:${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
